services:
  postgres:
    image: postgres:17.0
    hostname: localhost
    environment:
      POSTGRES_DB: ai-job-prep
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: